import Head from 'next/head'
import ModalWrapper from '../Components/UI/ModalWrapper'
import RegisterForm from '../Components/RegisterForm/RegisterForm'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Comércio Local Montijo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     

        <ModalWrapper>
          <RegisterForm />
        </ModalWrapper>
     

    </div>
  )
}
