import Head from 'next/head'
import ModalWrapper from '../Components/UI/ModalWrapper'
import RegisterForm from '../Components/RegisterForm/RegisterForm'
import Hero from '../Components/homepage/Hero'
import { useState, Fragment } from 'react'
import Categorias from '../Components/homepage/Categorias'

export default function Home() {

  const [registerModalOpen, setRegisterModalOpen] = useState(false)
  const [searchQuery, setSearchQuery] = useState({})

  return (
    <Fragment>
      <Head>
        <title>Comércio Local Montijo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero setQuery={setSearchQuery} />
      <Categorias />
      

      {registerModalOpen && <ModalWrapper><RegisterForm /></ModalWrapper>}




      <pre>
        {JSON.stringify(searchQuery, null, 2)}
      </pre>
    </Fragment>
  )
}
