import Head from 'next/head'
import ModalWrapper from '../Components/UI/ModalWrapper'
import RegisterForm from '../Components/RegisterForm/RegisterForm'
import Hero from '../Components/homepage/Hero'
import {useState} from 'react'

export default function Home() {

  const [registerModalOpen, setRegisterModalOpen] = useState(false)

  return (
    <div >
      <Head>
        <title>Comércio Local Montijo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
     
        {registerModalOpen && <ModalWrapper><RegisterForm /></ModalWrapper>}
     
    </div>
  )
}
